apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: test-ctie
  name: el-test-ctie-dev-route
  namespace: test-ctie-dev
spec:
  host: el-test-ctie-dev.apps.ocp-lab.its4u.eu
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-test-ctie-dev-eventlistener
    weight: 100
  wildcardPolicy: None